TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Aweme

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = DouyinMysteryUser

DouyinMysteryUser_FILES = Tweak.x
DouyinMysteryUser_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
